// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cztbrifwkbfsbmlsgipu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6dGJyaWZ3a2Jmc2JtbHNnaXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTkzMTQsImV4cCI6MjA3MTU3NTMxNH0.I4MRzjD4E_6rasd60vF65MDGi0LtnWWHvPuWI1PLmqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});